### ISSUE TITLE
get_bindings() does not clear primary binding's modifier key when using a secondary binding

### ISSUE THREAD

**Issue by xenophonf** [SumZer0-git/EDAPGui#15]
Given this key binding:

```
	<UseBoostJuice>
		<Primary Device="Keyboard" Key="Key_RightAlt">
			<Modifier Device="28DE11FF" Key="GamePad_FaceDown" />
		</Primary>
		<Secondary Device="Keyboard" Key="Key_Home" />
	</UseBoostJuice>
```

The get_bindings() throws a KeyError exception on line 122 in EDKeys.py:

```
                            binding['mod'] = SCANCODE[binding['pre_mod']]
```

The user sees the following error message, which violates the principle of least astonishment by not also reporting the modifier key:

```
Unrecognised key 'DIK_HOME' for bind 'UseBoostJuice'
```

The modifier key binding should be reset to `None` if a secondary key binding has been detected.  Add the following after line 100 in EDKeys.py:

```
                    mod = None
```

The subsequent `if` expression will set the modifier key of the secondary key binding if present.

**Comment by SumZer0-git** [comment]
fixed merged.   Good catch
