### ISSUE TITLE
Error while getting keybindings

### ISSUE THREAD

**Issue by DLAcoding** [SumZer0-git/EDAPGui#30]
When executing for the first time it says:

    Unrecognised key 'DIK_NUMPAD_SUBTRACT' for bind 'GalaxyMapOpen'

It seems is the opengalaxy button which I have binded to the minus sing in the block num pad

![image](https://user-images.githubusercontent.com/28142896/170091228-3791b3fd-8fc8-4783-a349-31355b331078.png)

**Comment by Matrixchung** [comment]
See https://github.com/SumZer0-git/EDAPGui/blob/main/directinput.py#L86
`DIK_SUBTRACT` should be renamed to `DIK_NUMPAD_SUBTRACT`

**Comment by SumZer0-git** [comment]
copy, merged.

**Comment by SumZer0-git** [comment]
merged DLAcoding fix
