### ISSUE TITLE
What did i wron 

### ISSUE THREAD

**Issue by SerdarSrl** [SumZer0-git/EDAPGui#38]
Hey there i am admire your work and i am trying to get this script work for a some time now. I did everything step by step what your suggest and ribigo mining works but not the fsd assist. Can't get this fsd assist to work. I try everything...

**Comment by SumZer0-git** [comment]
well, FSD Assist is pretty fundamental.  What seems to be happening?    Might be easier to jump over to the Discord and you can post thing there
